name: tedtalks

services:
  backend:
    build: .
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:12.22
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin123

volumes:
  db-data: